from typing import Protocol


class SupplyDataFunctions(Protocol): ...
class ExecuteFunctions(Protocol): ...
class PollFunctions(Protocol): ...
class TriggerFunctions(Protocol): ...
class WebhookFunctions(Protocol): ...
class LoadOptionsFunctions(Protocol): ...
class LocalLoadOptionsFunctions(Protocol): ...
class HookFunctions(Protocol): ...
